# Generated by Django 4.2.7 on 2024-01-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_image",
            field=models.ImageField(default="avatar.svg", null=True, upload_to=""),
        ),
    ]
